// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjYXTqCAjN4QzVYM6O077Jg0QkJPMjCaI',
    appId: '1:796279147680:web:2d26fe75cb4a9e61a38dc5',
    messagingSenderId: '796279147680',
    projectId: 'proectul-practic',
    authDomain: 'proectul-practic.firebaseapp.com',
    storageBucket: 'proectul-practic.firebasestorage.app',
    measurementId: 'G-EJYC3CWGSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHdQOJc9VTe3qGmQXRudD5GQi50NhsGNU',
    appId: '1:796279147680:android:ab1b48cdc8b50648a38dc5',
    messagingSenderId: '796279147680',
    projectId: 'proectul-practic',
    storageBucket: 'proectul-practic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArrvxxv_coVF0TZs01BKDV5_wet9kMeVg',
    appId: '1:796279147680:ios:9efd135b2867fe83a38dc5',
    messagingSenderId: '796279147680',
    projectId: 'proectul-practic',
    storageBucket: 'proectul-practic.firebasestorage.app',
    iosBundleId: 'com.example.proiectulpractic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArrvxxv_coVF0TZs01BKDV5_wet9kMeVg',
    appId: '1:796279147680:ios:9efd135b2867fe83a38dc5',
    messagingSenderId: '796279147680',
    projectId: 'proectul-practic',
    storageBucket: 'proectul-practic.firebasestorage.app',
    iosBundleId: 'com.example.proiectulpractic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjYXTqCAjN4QzVYM6O077Jg0QkJPMjCaI',
    appId: '1:796279147680:web:03c9593566ef3e96a38dc5',
    messagingSenderId: '796279147680',
    projectId: 'proectul-practic',
    authDomain: 'proectul-practic.firebaseapp.com',
    storageBucket: 'proectul-practic.firebasestorage.app',
    measurementId: 'G-DZ0HPS2BSN',
  );

}